AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: photoAlbumApp
Resources:
  photoAlbumApp1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: photoAlbumApp-LF1
      Handler: photoAlbumApp-LF1.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda
      Description: 'photoAlbumApp-LF1'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::604154134957:role/codepipeline_lambda'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1


  photoAlbumApp2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: photoAlbumApp-LF2
      Handler: photoAlbumApp-LF2.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda
      Description: 'photoAlbumApp-LF2'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::604154134957:role/codepipeline_lambda'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
